### ISSUE TITLE
Problem when try to print via iphone

### ISSUE THREAD

**Issue by ygarand** [zajac-grzegorz/homeassistant-addon-cups-airprint#9]
Hi,

I installed CUPS on my Home Assistant via Add-ons.  I try to print via Airprint with my iphone and I only have this papersize A3, A4, A5 but My printer in CUPS is set for Letter paper size.  Do you have solution ?  I don't find the config files in data/cups.

Thanks

**Comment by daltonpearson** [comment]
@ygarand sorry for reviving a closed issue but I'm having the same issue with the current build. How were you able to resolve the issue?

**Comment by daltonpearson** [comment]
For anyone who comes across this in the future the issue was that ReadyPaperSizes was the wrong value, it can be updated by exec'ing into the container and running the following:

```
cupsctl ReadyPaperSizes=Letter,A4,
lpadmin -p <Printer Name> -o share-printer=false
lpadmin -p <Printer Name> -o share-printer=true
```

would be nice if we could make this update automatically or even run something on container start to update ReadyPaperSizes with the common names for the values in `media-supported`
